created fetch mainsvc
Asror0314/java-explore-with-me pull request #5
Opened 2023-05-17 07:36 UTC by Asror0314

2023-05-24 21:11 UTC, sergeymamonov requested changes

2023-05-24 21:11 UTC, sergeymamonov commented on ewm-service/src/main/java/ru/yandex/explore/event/EventServiceImpl.java
> +    private void validLocation(Location location, LocationDto locationDto) {
Параметр locationDto не используется в методе.

2023-05-24 21:11 UTC, sergeymamonov commented on ewm-service/src/main/java/ru/yandex/explore/location/LocationMapper.java
> +    public static Location mapLocationDto2Location(LocationDto locationDto) {
Если 2 это сокращение для To, то лучше так не делать и использовать To.

2023-05-24 21:11 UTC, sergeymamonov commented on ewm-service/src/main/java/ru/yandex/explore/request/RequestServiceImpl.java
> +                    confirmRequests(request, event);
Запросы к БД в цикле.

2023-05-24 21:11 UTC, sergeymamonov commented on ewm-service/src/main/java/ru/yandex/explore/request/RequestServiceImpl.java
> +                    rejectRequest(request);
Запросы к БД в цикле.

2023-05-24 21:11 UTC, sergeymamonov commented on ewm-service/src/main/java/ru/yandex/explore/request/RequestServiceImpl.java
> +            throw new EditRulesException(String.format("event initiator id={} is mismatch", initiator.getId()));
Здесь нужно через %d.

2023-05-24 21:11 UTC, sergeymamonov commented on ewm-service/src/main/java/ru/yandex/explore/stats/StatsClient.java
>  public class StatsClient extends BaseClient {
Базовый клиент в одном модуле, а этот клиент в другом модуле. Так е делают. Перенесите StatsClient в модуль stats-client.

2023-05-25 05:56 UTC, Asror0314 commented on ewm-service/src/main/java/ru/yandex/explore/event/EventServiceImpl.java
> +        eventRepository.updateEventUser(eventId, eventDto.getAnnotation(), category, createdDate, eventDto.getDescription(),
Хорошо. Как исправлю основную ошибку, переделаю и эту

2023-05-25 06:37 UTC, Asror0314 commented on ewm-service/src/main/java/ru/yandex/explore/request/RequestServiceImpl.java
> +                    confirmRequests(request, event);
Не понял, что нужно делать?

2023-05-26 03:39 UTC, sergeymamonov commented on ewm-service/src/main/java/ru/yandex/explore/request/RequestMapper.java
> +            if (request.getStatus().equals(RequestStatus.CONFIRMED)) {
RequestStatus.CONFIRMED.equals(...)

2023-05-26 03:39 UTC, sergeymamonov commented on ewm-service/src/main/java/ru/yandex/explore/event/EventServiceImpl.java
> +    private void getCountHits(Event event) {
Метод ничего не возвращает, но при это называется get... Лучше переименовать, чтобы название соответствовало содержимому метода.

2023-05-26 03:39 UTC, sergeymamonov commented on ewm-service/src/main/java/ru/yandex/explore/request/RequestServiceImpl.java
> +            default: throw new RuntimeException(String.format("Unknown state: %s", requestInitiatorDto.getStatus()));
Лучше создать свое или кидать какое-то специфическое исключение, но не нужно кидать общее исключение. Потому что при разборе логов будет сложнее понять, то ли это ошибка в программе, то ли вы это предусмотрели и так и запланировали.

2023-05-26 03:39 UTC, sergeymamonov commented on ewm-service/src/main/java/ru/yandex/explore/request/RequestServiceImpl.java
> +                    confirmRequests(request, event);
Избавиться от запросов в цикле к БД.

2023-05-26 03:42 UTC, sergeymamonov approved these changes
Описание коммитов должно быть подробно. Не должно быть несколько коммитов с одинаковым названием. В коллективной разработке, ваши коллеги будут видеть ваши коммиты, вам может потребоваться откатиться на какой-то коммит. Если они все называются одинаково, то будет сложно понять, на какой откатываться.

2023-05-26 04:36 UTC, merged